spring:
  application:
    name: dogfile
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: "${DB_DDL_MODE}"

jwt:
  secret: "iHixb3jBQEqLIJCQvWgMnQKianUU50A7LcAf1gyQWHA"
  expiration: 100000000